modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/macuguita/set-time-doesn-t-reset-day-count/issues"
license = "GNU LGPL 3.0"

[[mods]]
modId = "set_time"
version = "${version}"
displayName = "Set time doesn't reset day count"
authors = "macuguita"
description = '''
This mod makes it so the set time command doesn't reset day count
'''
logoFile = "assets/set_time/icon.png"
displayURL = "https://github.com/macuguita/set-time-doesn-t-reset-day-count"

[[dependencies.set_time]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.set_time]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "NONE"
side = "SERVER"

